# startship
eval "$(starship init zsh)"

# for antigen
source /Users/yankuihao/antigen.zsh
antigen use oh-my-zsh
# plugins
antigen bundle git
antigen bundle command-not-found
antigen bundle colored-man-pages
antigen bundle history-substring-search
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle jeffreytse/zsh-vi-mode
# need brew install z
# Tell Antigen that you're done.
antigen apply

# shortcuts
# for history-substring
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
# for 
bindkey '^F' autosuggest-accept

# completion settings
# 加载自定义补全脚本
fpath=(~/.zsh/completions $fpath)
autoload -Uz compinit
compinit


# set homebrew tuna mirror
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
export HOMEBREW_PIP_INDEX_URL="https://pypi.tuna.tsinghua.edu.cn/simple"

# set linux utils for mac
# https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/opt/file-formula/bin:$PATH"
export MANPATH="/opt/homebrew/opt/coreutils/libexec/gnuman:$MANPATH"
export MANPATH="/opt/homebrew/opt/file-formula/share/man/man1:$MANPATH"

# jdk
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
# local bin
export PATH="$PATH:/Users/yankuihao/.local/bin"

# set android emulator
alias kAndroidEmulator="/opt/homebrew/share/android-commandlinetools/emulator/emulator -avd m1android"
alias icat="kitty +kitten icat"
alias kssh="kitty +kitten ssh"

# doom sync
alias doom="~/.config/emacs/bin/doom"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# flutter
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
export CHROME_EXECUTABLE="/Applications/Chromium.app/Contents/MacOS/Chromium"

alias pemacs="https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 emacs -nw"
